name: loan_calculator
description: A production-ready, multi-language Loan Calculator app in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#1976D2"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#1976D2"
    image: assets/images/splash_logo.png
